# Generated by Django 4.2.1 on 2023-06-18 09:20

import apps.appFiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_url', models.FileField(upload_to=apps.appFiles.models.upload_to)),
                ('url_to_upload', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
