# Generated by Django 4.2.1 on 2023-06-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='directory',
            field=models.CharField(default='', max_length=50),
        ),
    ]
