# Generated by Django 4.2.1 on 2023-06-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('link', models.URLField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=250, null=True)),
                ('last_name', models.CharField(default=None, max_length=250, null=True)),
                ('patronymic', models.CharField(default=None, max_length=250, null=True)),
                ('date_of_birth', models.DateField(default=None, null=True)),
                ('telephone', models.CharField(max_length=20, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Персональная информация',
            },
        ),
    ]
